### ISSUE TITLE
Suggest free forums that we can use

### ISSUE THREAD

**Issue by aviaryan** [iiitv/coding_club#1]
We would like to have a forum for IIITV coding club where students can raise their doubts, create topics and get answered. 
Slack is not suitable for this as it is a chat-based service.
Here is an example forum that will work: https://autohotkey.com/boards/
Please suggest any free services we can use to setup our forum.

**Comment by aviaryan** [comment]
@iiitv/club_friends any suggestions?

**Comment by singhpratyush** [comment]
How about Github issues? `markdown` is good for discussions.

**Comment by boddumanohar** [comment]
gitter?

**Comment by aviaryan** [comment]
> How about Github issues? markdown is good for discussions.

Good idea. I too had it in mind. But we should use it only if nothing else comes up. The problems with Github are-- 

1. You can't create sub-forums, we can use tags but there is no real hierarchy. But maybe right now, we won't miss sub-forums as there won't be many posts. 
2. No user post counts - Believe me, this can be a very motivating factor for people to stay active on forum and help others.
3. No user signatures, crazy avatars and other fun stuff. These keep forum members interested.
4. Very limited in features. Can get boring because it's Github, same atmosphere. 

I have been active on a phpBB forum for a  couple of years and made over 1500 posts so I can say that those type of forums have something special about them. (There was this other guy who made over 20 posts per day.., it's fun)

> gitter?

No. Gitter is chat.

**Comment by boddumanohar** [comment]
[Disclosure](http://www.discourse.org/). 
1. Tags & categories 
2. Markdown also supported 

But the problem is its need to be hosted in a web server.

**Comment by aviaryan** [comment]
I am trying to setup a forum on http://prophpbb.com . It's been around for years so we can assume it is a reliable service. 

> But the problem is its need to be hosted in a web server.

Also Discourse forums are very limited. Except from my first point mentioned in https://github.com/iiitv/coding_club/issues/1#issuecomment-274078812, discourse satisfies all others (negative sense). So no for now. Thanks for the input.

**Comment by aviaryan** [comment]
A forum has been created. http://iiitv.prophpbb.com
Please create your accounts preferably with college email id.
