### ISSUE TITLE
Send applications for Coder class

### ISSUE THREAD

**Issue by aviaryan** [iiitv/coding_club#2]
Send your proposals to me if you think you can be part of Coder class. For now, send your proposals to my email id (avi(dot)aryan123(at)gmail). We should have an official coding club id soon enough :). 

The proposal should include your assessment in the [given attributes](https://github.com/iiitv/coding_club#coder-quality-attributes). 
Please be descriptive and provide proofs wherever possible.

**Comment by singhpratyush** [comment]
I feel like we should keep these proposals in Github issues for transparency.
