### ISSUE TITLE
Send applications for Organizer class

### ISSUE THREAD

**Issue by aviaryan** [iiitv/coding_club#4]
We will need volunteers who will like to help organise events for coding club. 
Please reply back on this thread if you are interested. 

cc @pcsaini @geekyJock8 @singhpratyush @7ranveer @Monal5031 @yashLadha

**Comment by yashLadha** [comment]
Yes i am interested but i am inclined to developer side more @aviaryan

**Comment by 7ranveer** [comment]
Interested!

**Comment by aviaryan** [comment]
@7ranveer added you to organizers team. 
@yashLadha please follow the process mentioned at #2 so that I can add you to Coder class.

**Comment by singhpratyush** [comment]
Interested.

**Comment by aviaryan** [comment]
@singhpratyush Added to team

**Comment by pcsaini** [comment]
yes i am interested

**Comment by aviaryan** [comment]
@pcsaini Done. Please help with #7
