### ISSUE TITLE
Get started with a workshop

### ISSUE THREAD

**Issue by aviaryan** [iiitv/coding_club#6]
Do a workshop. Just start.

### Ideas

* Python - https://github.com/iiitv/workshops/issues/3 - 2nd year
* Intro to Programming - https://github.com/iiitv/workshops/issues/9 - 1st year

.. suggest more

Please reply if you are interested in giving a session.

**Comment by RajuKoushik** [comment]
Interested - Python Workshop !!

**Comment by aviaryan** [comment]
@iiitv/club_organizers We would like to have a Python workshop for 2nd year. The workshop will be conducted by @RajuKoushik , @KamalAwasthi and probably (@singhpratyush ?) . 
Please notify here ASAP of the free slots available.

**Comment by aviaryan** [comment]
GSoC workshop has been successfully conducted on 3rd Feb. Hence closing.
