### ISSUE TITLE
Find slots to conduct sessions

### ISSUE THREAD

**Issue by aviaryan** [iiitv/coding_club#7]
Please in this issue, list the empty slots available for each batch so that it can serve as a reference when someone is going to organise session. 

@saurabhnitnaware I have sent you iiitv group invite. Please accept it so that you can formally be a part of the process. 

cc @iiitv/club_organizers

**Comment by yashLadha** [comment]
for 2nd year
IT: Friday - 3:00
    Thursday - 2:00

CS: Friday - 2:00

**Comment by aviaryan** [comment]
@yashLadha Any place where both CS and IT are free simultaneously?

**Comment by pcsaini** [comment]
Friday 4PM to 6PM 2nd year and 3rd both are free.

**Comment by yashLadha** [comment]
Friday will be free for both cs and it for 2 year
